#version: '3'
#services:
#  springboot:
#    build: .
#    restart: always
#    container_name: bootdockercontainer
#    ports: 8081:8081
#    working_dir: /opt/app
#    depends_on:
#      - postgres
#  test:
#    image: openjdk:8-jdk-alpine
#    links:
#      - postgres
#  postgres:
#    image: "postgres:9.6.11-alpine"
#    ports:
#      - 5433:5432
#    environment:
#      - POSTGRES_PASSWORD=boehringer
#      - POSTGRES_USER=boehringer
#      - POSTGRES_DB=boehringer
version: '3.1'
services:
  auth-api:
    container_name: auth-api
    image: auth-api
    build: auth-api
    ports:
      - 8080:8080
  resource-server:
    container_name: resource-server
    image: resource-server
    build: resource-server
    ports:
      - 8081:8081
    depends_on:
      - postgres
      - auth-api
  postgres:
    container_name: postgres
    image: "postgres:9.6.11-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=boehringer
      - POSTGRES_USER=boehringer
      - POSTGRES_DB=boehringer


