spring:
  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: true
  datasource:
    url: "jdbc:postgresql://postgres:5432/boehringer"
    username: boehringer
    password: boehringer
  jpa:
    properties:
      hibernate:
        generate_statistics: true

server:
  port: 8081
security:
  oauth2:
    client:
      clientId: exampleClient
      clientSecret: exampleSecret
    resource:
      token-info-uri: http://auth-api:8080/oauth/check_token
#logging:
#  level:
#    root: DEBUG
#    org:
#      springframework:
#        web: DEBUG